### ISSUE TITLE
Queue server times out any other players aside from the first one that joins the queue

### ISSUE THREAD

**Issue by 12yl** [McMackety/velocity-queue#17]
Issue is in the title

Queue config:
![Screenshot 2021-06-15 10 06 16 PM](https://user-images.githubusercontent.com/85979858/122161577-d1de0680-ce26-11eb-811c-8ee708093854.png)

Velocity config:
![Screenshot 2021-06-15 10 09 33 PM](https://user-images.githubusercontent.com/85979858/122161633-e4584000-ce26-11eb-88b3-0c901923a5c7.png)

**Comment by McMackety** [comment]
Alright, so it looks like you're listing two limbo servers, one called `queue` and one called `limbo`. The first thing you should do is remove the one named `limbo` from the `settings.limboServers` array. After that remove the `maxPlayersOverride` line as that's not formatted correctly, though it shouldn't cause any issues. Finally, disable the intra-server queue as you don't need to enable the intra-server queue for the server you first drop players into.

**Comment by McMackety** [comment]
If you don't get what I mean by that post your config as text and I'll quickly fix it.

**Comment by 12yl** [comment]
Hi, thank you for the help, I've changed the config to look like this now:

```
---
settings:
  limboServers:
  - name: "queue"
    maxPlayers: 100
  joinQueue:
    enabled: true
    joinedQueueMessage: "You've joined the queue."
    oneLessPlayerInQueueMessage: ""
    playerInQueueTimePerMessage: 10000
    lastPlayerInQueueMessage: ""
    joinedServerMessage: ""
  priorityQueueMultiplier: 10
  intraServerQueue:
    enabled: false
    queuedServers:
    - "main"
    millisecondsPerPlayer: 1000
    joinedQueueMessage: ""
    oneLessPlayerInQueueMessage: ""
    playerInQueueTimePerMessage: 10000
    lastPlayerInQueueMessage: ""
    joinedServerMessage: ""
  leftQueueMessage: ""
  notInQueueMessage: ""
  queueBackend: "local"
```


Is this how it should look?
